#!/bin/sh
# battery %:		/sys/class/power_supply/BAT0/capacity
# charging state:	/sys/class/power_supply/BAT0/status
# charger plugged in:	/sys/class/power_supply/AC0/online
pwrDir="/sys/class/power_supply"
batDir="$pwrDir/BAT0"
capacityFile="$pwrDir/BAT0/capacity"
chargingFile="$pwrDir/AC0/online"

chargingIcon="\u202dﮣ\u202c"
echo -e '<>'
[ -d "$batDir" ] || exit

if [ ! -f "$capacityFile" -o ! -f "$chargingFile" ]; then
    echo "BAT:??"
    echo "BAT:??"
    echo "#e06c75"
    exit
fi

capacity=(( <"$capacityFile" ))
charging=(( <"$chargingFile" ))

# 
# ﮣ
# 


#[[ $(</sys/class/power_supply/AC0/online) -eq 1 ]] && charging="ﮣ" || charging="ﮤ"
# NOTE: \ufba3 and \ufba4 (plug and crossed-out plug icons above) are right-to-left characters, so we have to use unicode control characters to override their text direction
# \u202d (LEFT-TO-RIGHT OVERRIDE) Overrides bidirectional text algorithm to display characters in left to right order
# \u202c (POP DIRECTIONAL FORMATTING) Closing text direction tag
#output="\u202d$capacity% $charging\u202c"

#TODO: Set colour on capacity inticator based on battery percentage
#echo -e "<span>$capacity%</span> \u202d$charging\u202c"

