#!/bin/sh
# battery %:		/sys/class/power_supply/BAT0/capacity
# charging state:	/sys/class/power_supply/BAT0/status
# charger plugged in:	/sys/class/power_supply/AC0/online
pwrDir="/sys/class/power_supply"
batDir="$pwrDir/BAT0"
capacityFile="$pwrDir/BAT0/capacity"
chargingFile="$pwrDir/AC0/online"

#[ -d "$batDir" ] || exit

if [ ! -f "$capacityFile" -o ! -f "$chargingFile" ]; then
    echo " BAT:?? "
    echo " BAT:?? "
    exit
fi

batteryIcons=( "" "" "" "" "" "" "" "" "" "" )
chargingIcon="\u202dﮣ\u202c"

(( <($chargingFile) )) && charging=$(echo -e " <span rise=\"1pt\" size=\"small\">\u202dﮣ\u202c</span>")

capacity=(( <"$capacityFile" ))
if [ "$capacity" -ge 95 ]; then
    echo " <span size=\"medium\" color=\"#00ff00\">${batteryIcons[9]}</span>$charging "
else
    if [ "$capacity" -gt 40 ]; then
        echo " <span size=\"medium\">${batteryIcons[((capacity/10))]}</span>$charging "
    elif [ "$capacity" -gt 10 ]; then
        echo " <span size=\"medium\" color=\"#e5c07b\">${batteryIcons[((capacity/10))]}</span>$charging "
    else
        echo " <span size=\"medium\" color=\"#e06c75\">${batteryIcons[((capacity/10))]}</span>$charging "
    fi

fi

