#!/bin/sh
case "$1" in
	on)		echo "Outputting to HDMI1" && xrandr --output HDMI1 --auto --primary --output eDP1 --off ;;
	off)	echo "Outputting to eDP1"  && xrandr --output eDP1 --auto --primary --output HDMI1 --off ;;
	*) cat << _end
Usage: txm [on|off]
Toggles an external monitor (HDMI1) on or off
_end
esac
