#!/bin/sh

HOSTS=$(\
  dig @172.16.0.2 -tAXFR hlab.internal |\
  sed -n 's/^\([[:graph:]]\+\.hlab\.internal\).*[[:space:]]A[[:space:]]*\([[:graph:]]\+\)$/\2,\1/p'\
)
update-hosts -d 'VMWARE-HLAB.INTERNAL' -c 'vmware hlab.internal hosts' ${HOSTS[@]}
